version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
   configuration: docs/source/conf.py

formats:
   - pdf
   - epub

python:
   install:
   - method: setuptools
     path: .
   - requirements: docs/requirements.txt
