version: 2

build:
  os: ubuntu-22.04

sphinx:
   configuration: docs/source/conf.py

formats:
   - pdf
   - epub

python:
   version: 3.8
   install:
   - method: setuptools
     path: .
   - requirements: docs/requirements.txt
