version: 2

sphinx:
   configuration: docs/source/conf.py

formats:
   - pdf
   - epub

python:
   version: 3.10
   install:
   - method: setuptools
     path: .
   - requirements: docs/requirements.txt
