name: pupyl-ci

on: [push]

jobs:

  setup:
    runs-on: ubuntu-latest
    name: setup
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8 pylint mypy types-termcolor pytest pytest-cov
        python setup.py install

  pep8:
    runs-on: ubuntu-latest
    needs: [setup]
    name: pep-8
    steps:
    - name: Check conformance with PEP-8 using flake8
      run: make flake8

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    name: linter
    steps:
    - name: Linter with pylint
      run: make linter

  static:
    needs: [setup]
    runs-on: ubuntu-latest
    name: static-check
    steps:
    - name: Static type checking
      run: make static-check

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    name: tests
    steps:
    - name: Unit tests
      run: make test

  coverage:
    needs: [setup, test]
    runs-on: ubuntu-latest
    name: coverage
    steps:
    - name: Coverage report
      run: make coverage

  codecov:
    needs: [coverage]
    runs-on: ubuntu-latest
    name: codecov-upload
    steps:
    - name: Uploads test coverage results to CodeCov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
