name: pupyl-ci

on: [push]

jobs:

  pep8:
    runs-on: ubuntu-22.04
    name: pep8
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Check conformance with PEP-8 using flake8
      run: |
        pip install --upgrade pip
        pip install flake8
        make flake8

  lint:
    runs-on: ubuntu-22.04
    name: lint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Linter with pylint
      run: |
        pip install --upgrade pip
        pip install pylint
        python setup.py install
        make linter

  static:
    runs-on: ubuntu-22.04
    name: static-check
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Static type checking
      run: |
        pip install --upgrade pip
        pip install mypy types-termcolor
        make static-check

  test:
    runs-on: ubuntu-22.04
    name: test
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Unit tests
      run: |
        pip install --upgrade pip
        pip install pytest
        python setup.py install
        make test

  coverage:
    runs-on: ubuntu-22.04
    name: coverage
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Coverage report
      run: |
        pip install --upgrade pip
        pip install pytest pytest-cov
        python setup.py install
        make coverage

  codecov:
    needs: [coverage]
    runs-on: ubuntu-22.04
    name: codecov-upload
    steps:
    - name: Uploads test coverage results to CodeCov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
