name: pupyl-ci

on: [push]

jobs:
  build:

    name: Build and tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        make flake8
    - name: Tests and coverage
      run: |
        pip install pytest pytest-cov
        make test
        make coverage
