name: pupyl-ci

on: [push]

jobs:
  build:

    name: Build and tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Lint with flake8
      run: |
        pip install flake8
        make flake8
    - name: Tests
      run: |
        pip install pytest pytest-cov
        make test
    - name: Coverage report
      run: make coverage
    - name: CodeCov upload
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
