name: pupyl-ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        make flake8
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        make test
    - name: Test coverage with pytest-cov
      run: |
        pip install pytest pytest-cov
        make coverage
